lookupEventDspFsmStates = function(v) {
    switch(v) {
case 1: return "DID_BOOT"; break;
case 2: return "DO_WAIT"; break;
case 3: return "COARSE_0"; break;
case 4: return "WAIT_COARSE_0"; break;
case 5: return "FINISH_COARSE_0"; break;
case 6: return "TIMING_0"; break;
case 7: return "SFO_CFO_0"; break;
case 8: return "TIMING_0_WAIT"; break;
case 9: return "TIMING_0_GOT_PHASE"; break;
case 10: return "TIMING_0_GOT_PHASE_FINAL"; break;
case 12: return "DO_WAIT_1"; break;
case 13: return "COARSE_1"; break;
case 14: return "FINISH_COARSE_1"; break;
case 15: return "TIMING_1"; break;
case 17: return "TIMING_1_WAIT"; break;
case 18: return "TIMING_1_GOT_PHASE"; break;
case 19: return "TIMING_1_GOT_PHASE_FINAL"; break;
case 20: return "BEAMFORM_SETUP"; break;
case 21: return "BEAMFORM_DO_IT"; break;
case 22: return "BEAMFORM_CHILL"; break;
case 23: return "BEAMFORM_PRE_0"; break;
case 24: return "BEAMFORM_PRE_1"; break;
case 25: return "COARSE_SCHEDULE_0"; break;
case 26: return "COARSE_SCHEDULE_SENT_N"; break;
case 29: return "COARSE_SYMBOL_SENT_0"; break;
case 30: return "CORASE_SCHEDULE_DELAY_0"; break;
case 31: return "CORASE_SYMBOL_WAIT_0"; break;
case 27: return "COARSE_TIMING_1"; break;
case 28: return "COARSE_TIMING_SENT_1"; break;
case 32: return "SFO_STATE_0"; break;
case 33: return "STO_0"; break;
case 34: return "CFO_0"; break;
case 35: return "COARSE_SCHEDULE_1"; break;
case 36: return "CORASE_SCHEDULE_DELAY_1"; break;
case 37: return "CORASE_SYMBOL_WAIT_1"; break;
case 38: return "WAIT_COARSE_1"; break;
case 39: return "SFO_STATE_1"; break;
case 40: return "STO_1"; break;
case 41: return "CFO_1"; break;
case 42: return "SFO_CFO_1"; break;
case 43: return "TRANSITION_0_TO_1"; break;
case 44: return "AFTER_COARSE_1"; break;
case 45: return "PRE_BOOT"; break;
case 46: return "PRE_BOOT_2"; break;
case 47: return "WAIT_FOR_PEERS"; break;
case 48: return "TICKLE_PEERS"; break;
case 49: return "TICKLE_PEERS_1"; break;
case 50: return "TICKLE_PEERS_2"; break;
case 51: return "TICKLE_PEERS_3"; break;
case 52: return "TICKLE_PEERS_4"; break;
case 53: return "TICKLE_PEERS_5"; break;
case 60: return "FINE_SYNC"; break;
case 61: return "BACKGROUND_SYNC"; break;
case 62: return "DO_TRIGGER_0"; break;
case 63: return "WAIT_FOR_RADIO_TO_FINE_0"; break;
case 64: return "PRE_SFO_STATE_0"; break;
case 65: return "AFTER_FINE_1"; break;
case 66: return "WAIT_FOR_RADIO_TO_FINE_1"; break;
case 67: return "DO_TRIGGER_1"; break;
case 68: return "GOT_TDMA_REQUEST"; break;
case 69: return "TDMA_STATE_0"; break;
case 70: return "TDMA_STATE_1"; break;
case 71: return "TDMA_STATE_2"; break;
case 72: return "TDMA_STATE_3"; break;
case 73: return "WAIT_EVENTS"; break;
case 74: return "PRE_COARSE_SCHEDULE_0"; break;
case 75: return "SETUP_COARSE_SCHEDULE_0"; break;
case 76: return "WAIT_COARSE_SCHEDULE_0"; break;
case 77: return "COARSE_SCHEDULE_FINISHED_0"; break;
case 78: return "WAIT_FOR_RADIO_0_EQ"; break;
case 79: return "WAIT_AGAIN_FOR_RADIO_0_EQ"; break;
case 80: return "FINE_SCHEDULE_0"; break;
case 81: return "PRE_FINE_SCHEDULE_0"; break;
case 82: return "WAIT_FINE_SCHEDULE_0"; break;
case 83: return "FINE_SCHEDULE_1"; break;
case 84: return "PRE_FINE_SCHEDULE_1"; break;
case 85: return "WAIT_FINE_SCHEDULE_1"; break;
case 86: return "COARSE_SYNC_ADJ_0"; break;
case 87: return "STO_EQ_0"; break;
case 88: return "TICKLE_PEERS_3_DOT_5"; break;
case 89: return "AFTER_PRE_BOOT"; break;
case 90: return "DEBUG_PERF_0"; break;
case 91: return "DEBUG_PERF_1"; break;
case 92: return "DEBUG_PERF_2"; break;
case 93: return "DEBUG_PERF_3"; break;
case 94: return "DEBUG_PERF_4"; break;
case 95: return "TX_STALL"; break;
case 96: return "DEBUG_PEER_PERFORMANCE_0"; break;
case 97: return "DEBUG_PEER_PERFORMANCE_1"; break;
case 98: return "DEBUG_PEER_PERFORMANCE_2"; break;
case 99: return "TICKLE_PEERS_3_DOT_6"; break;
case 100: return "TICKLE_PEERS_3_DOT_7"; break;
case  101: return "WAIT_FOR_RADIO_1_EQ"; break;
case  102: return "TICKLE_PEERS_3_DOT_55"; break;
case 103: return "DEBUG_EQ_ROT_PRE"; break;
case 104: return "DEBUG_EQ_ROT_0"; break;
case 105: return "DEBUG_EQ_ROT_1"; break;
case 106: return "TDMA_STATE_2_DOT_5"; break;
case 107: return "TDMA_STATE_2_DOT_6"; break;
case 108: return "TDMA_STATE_2_DOT_7"; break;
case 109: return "TDMA_STATE_2_DOT_55"; break;
case 110: return "SET_SFO_INIT_0 "; break;
case 111: return "SET_RANDOM_ROTATION "; break;
case 112: return "TEST_COARSE_SYNC_DROP_0 "; break;
case 113: return "TEST_COARSE_SYNC_DROP_1 "; break;
case 114: return "TEST_COARSE_SYNC_DROP_2 "; break;
case 115: return "TEST_COARSE_SYNC_DROP_3 "; break;



case 0xffff0000: return "__UNSET_NEXT__"; break;
case 9999: return "DEBUG_STALL"; break;
default: return "?"; break;
    }
}